<?php

$users = array(
    'id' => array(
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
    ),
    'login' => array(
        'Antony',
        'Dinh',
        'Patrice',
        'Didier',
        'Roger',
        'Jean-pierre',
        'Christelle',
        'Emma',
        'Oasis',
    ),
    'password' => array(
        '1111',
        '2222',
        '3333',
        '4444',
        '5555',
        '6666',
        '7777',
        '8888',
        '9999',
    ),
    'email' => array(
        'antony@mail.com',
        'dinh@mail.com',
        'Patrice@mail.com',
        'Didier@mail.com',
        'Roger@mail.com',
        'Jean-pierre@mail.com',
        'Christelle@mail.com',
        'Emma@mail.com',
        'Oasis@mail.com',
    ),
);

$articles = array(
    'id' => array(
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
    ),
    'title' => array(
        'Chaise',
        'OrDinhateur',
        'Bureau',
        'Fenêtre',
        'Serveur 16GB',
        'Bouteille d\'eau',
        'Lunettes',
        'Stylo',
        'Clavier',
    ),
    'description' => array(
        'Une jolie Chaise',
        'Une jolie OrDinhateur',
        'Une jolie Bureau',
        'Une jolie Fenêtre',
        'Une jolie Serveur 16GB',
        'Une jolie Bouteille d\'eau',
        'Une jolie Lunettes',
        'Une jolie Stylo',
        'Une jolie Clavier',
    ),
    'prix' => array(
        17,
        27,
        37,
        47,
        57,
        67,
        77,
        87,
        97,
    ),
);